### ISSUE TITLE
kf5-kdoctools Could NOT find PerlModules_URI::Escape

### ISSUE THREAD

**Issue by jconley** [haraldF/homebrew-kf5#103]
```-- Found Perl: /usr/local/bin/perl (found version "5.24.1")
-- Could NOT find PerlModules_URI::Escape (missing:  PerlModules_URI_Escape_FOUND)
CMake Error at /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
```

resolved by manually installing URI::Escape
should the formula ensure it's installed?

macos 10.12.5

**Comment by haraldF** [comment]
Good question :) Are you using homebrew's perl or Mac OS X's perl?

There isn't much in the docs (https://github.com/Homebrew/brew/blob/master/docs/Gems,-Eggs-and-Perl-Modules.md). The extract_url.rb formula uses e.g.:

```ruby
  resource "URI::Find" do
    url "https://cpan.metacpan.org/authors/id/M/MS/MSCHWERN/URI-Find-20160806.tar.gz"
    sha256 "e213a425a51b5f55324211f37909d78749d0bacdea259ba51a9855d0d19663d6"
  end
```

and then some magic to be able to use it without sudo.

Are you up for playing around with the formula? :)

**Comment by franklinyu** [comment]
I came across this very issue. I think I am using Homebrew Perl because the log says

```text
-- Found Perl: /usr/local/bin/perl (found version "5.26.0")
```

So the module is actually not pre-installed? Is there a better way other than to mess with system Perl?

**Comment by jconley** [comment]
@franklinyu the current formula should install it automatically.  try running `cpanm URI` and see if you get any errors/output.

**Comment by yurikoles** [comment]
@jconley I had disabled this because of #127

**Comment by franklinyu** [comment]
Sorry I didn't see the caveat earlier. Yes, the `cpanm URI` installed `URI` (along with its dependency `Test::Needs`) and helped. I guess the Perl packages are installed at

```text
$(brew --cellar perl)/5.26.0/lib/perl5/site_perl/5.26.0
```

are they? This looks version-specific, so I may need to install `URI` every time I upgrade my Brewed Perl, do I?

I'm new to Perl, so I made some assumptions based on my experience on Python and Ruby.

**Comment by franklinyu** [comment]
I'm quite interested in @haraldF's suggestion. This practise has been the standard way in Python, as explained in [*Python for Formula Authors*](https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md). I think it is similar for Perl, so the "hack" of [`extract_url`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/extract_url.rb) may turn out to be quite future-proof.

**Comment by seltzered** [comment]
FWIW, I just ran into a similar issue while trying to `brew install okular` where build stopped at kdoctools, but was fixed by following the suggestions of doing `brew install cpanminus` then `cpanm URI`. Coming as someone new to kde-mac and perl.

```
==> Summary
🍺  /usr/local/Cellar/libxslt/1.1.33_1: 137 files, 2.8MB
==> Installing kde-mac/kde/okular dependency: KDE-mac/kde/kf5-kdoctools
==> Downloading https://download.kde.org/stable/frameworks/5.56/kdoctools-5.56.0
==> Downloading from http://mirror.cc.columbia.edu/pub/software/kde/stable/frame
######################################################################## 100.0%
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE
Last 15 lines from /Users/thisuser/Library/Logs/Homebrew/kf5-kdoctools/01.cmake:
-- Found Perl: /usr/local/bin/perl (found version "5.28.1") 
-- Could NOT find PerlModules_URI::Escape (missing: PerlModules_URI_Escape_FOUND) 
CMake Error at /usr/local/Cellar/cmake/3.14.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PerlModules (missing: PerlModules_all_modules_found
  URI::Escape)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPerlModules.cmake:77 (find_package_handle_standard_args)
  cmake/uriencode.cmake:34 (find_package)
  src/CMakeLists.txt:4 (kdoctools_encode_uri)
```

**Comment by yurikoles** [comment]
`"$(brew --repo kde-mac/kde)/tools/all-fixes.sh"`
