### ISSUE TITLE
Why KDevelop is HEAD only?

### ISSUE THREAD

**Issue by franklinyu** [haraldF/homebrew-kf5#118]
Latest stable (5.1.1) is available [here](https://download.kde.org/stable/kdevelop/5.1.1/src/). `kdevplatform` is also available there; I didn't find `kdevelop-pg-qt` though.

**Comment by krf** [comment]
kdevelop-pg-qt is here: https://download.kde.org/stable/kdevelop-pg-qt/

Feel free to update the formula!

**Comment by yurikoles** [comment]
fixed in ec1faadbe3686d4c4022de7036b41ca5eb8902d2
