### ISSUE TITLE
an issue installing kate

### ISSUE THREAD

**Issue by lucien1011** [haraldF/homebrew-kf5#12]
Hi I followed the procedures given on the readme.md and got stuck when trying to execute the line:
brew install --HEAD haraldf/kf5/kf5-kate

This error is like this:
==> Cloning git://anongit.kde.org/kate.git
Updating /Library/Caches/Homebrew/kf5-kate--git
==> Checking out branch frameworks
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kate/HEAD -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_CXX_FLAGS='-D_DARWIN_C_SOURCE'
==> make install
1 error generated.
make[2]: *** [kate/src/CMakeFiles/kdeinit_kate.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [kate/src/CMakeFiles/kdeinit_kate.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/haraldf/homebrew-kf5/issues

I have  kf5-karchive-4.98.0. I am not sure what is going on. Would you mind helping me a bit? Thank you very much.

**Comment by krf** [comment]
Still a problem? Most of the output is cut off => Cannot help
