### ISSUE TITLE
kf5-kate wrong shasum

### ISSUE THREAD

**Issue by bmihaila** [haraldF/homebrew-kf5#140]
The kate build script at https://github.com/haraldF/homebrew-kf5/blob/e390c060a60096947160d903d6f4244a1ab80083/kf5-kate.rb contains a wrong shasum for the downloaded package. Might be from an older version still there? As this commit https://github.com/haraldF/homebrew-kf5/commit/12e3d78a8e2aeeb78a5af15badd97ed91b9ce603#diff-afe17122f32b818468becd1bc89f6007 shows the shasum has not been updated on version bump.

This leads to an error during install:
```
==> Upgrading 1 outdated package, with result:
haraldf/kf5/kf5-kate 17.08.0
==> Upgrading haraldf/kf5/kf5-kate 
==> Downloading https://download.kde.org/stable/applications/17.08.0/src/kate-17.08.0.tar.xz
==> Downloading from http://ftp.ussg.iu.edu/kde/stable/applications/17.08.0/src/kate-17.08.0.tar.xz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 34eee6c384e2c2776c7d0ab65e7217e730cdbdecb82578c9dc90380cb82affd2
Actual: f25a39c7e272713940e82d53c1e8b266cf1d7acad3eeb7dd229f166fc8e0667d
Archive: /Users/bmihaila/Library/Caches/Homebrew/kf5-kate-17.08.0.tar.xz
To retry an incomplete download, remove the file above.
```

The right shasum for that download seems to be this:
`f25a39c7e272713940e82d53c1e8b266cf1d7acad3eeb7dd229f166fc8e0667d`
but check yourself to be sure ;)
```
wget https://download.kde.org/stable/applications/17.08.0/src/kate-17.08.0.tar.xz
shasum -a 256 kate-17.08.0.tar.xz
f25a39c7e272713940e82d53c1e8b266cf1d7acad3eeb7dd229f166fc8e0667d  kate-17.08.0.tar.xz
```

**Comment by yurikoles** [comment]
fixed in 1382c2e4a8e85125d1baee201d301839dab079c6
