### ISSUE TITLE
Phonon fails to install (while trying to install konsole)

### ISSUE THREAD

**Issue by corelon** [haraldF/homebrew-kf5#40]
This is the error I get

🍺  /usr/local/Cellar/kf5-kiconthemes/5.10.0: 109 files, 760K, built in 9 seconds
==> Installing haraldf/kf5/kf5-konsole dependency: haraldf/kf5/kf5-phonon
==> Downloading http://download.kde.org/stable/phonon/4.7.1/phonon-4.7.1.tar.xz
==> Downloading from http://www.mirrorservice.org/sites/ftp.kde.org/pub/kde/stable/phonon/4.7.1/phonon-4.7.1.tar.xz
######################################################################## 100.0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-phonon/4.7.1 -DCMAKE_BU
==> make install
1 error generated.
make[2]: *** [phonon/CMakeFiles/phonon4qt5.dir/pulsesupport.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [phonon/CMakeFiles/phonon4qt5.dir/all] Error 2
make: *** [all] Error 2

**Comment by krf** [comment]
Installing kf5-phonon works fine for me. Still a problem?

Notice you're also missing most of the debug output

**Comment by krf** [comment]
Closing for now
