### ISSUE TITLE
kdoctools fails to build

### ISSUE THREAD

**Issue by seanhoughton** [haraldF/homebrew-kf5#41]
The batch installer script doesn't work so I tried to build Kate assuming it will pull in most of the dependent libraries. However, it fails pretty quickly with a directory error. I've been trying to debug this myself but i'm not a cmake expert.

==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdoctools/5.10.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DDocBookXML_CURREN
==> make install
Error: No such file or directory - (/usr/local/Cellar/kf5-kdoctools/5.10.0/share/kf5, /private/tmp/kf5-kdoctools20150805-42830-1pkcq5b/kdoctools-5.10.0/.brew_home/Library/Application Support/kf5)
sean-mbp:~ seanhoughton$

**Comment by soxwellfb** [comment]
Also seeing this issue. :(

**Comment by mccann** [comment]
Hi, I was able to fix this issue by editing the kf5-kdoctools.rb formula

Apparently, the HOME env variable is not the usual /Users/$USER path at that point in script execution.
Found an alternative way to get the same value.

```
diff --git a/kf5-kdoctools.rb b/kf5-kdoctools.rb
index 7c2eb19..393cc5e 100644
--- a/kf5-kdoctools.rb
+++ b/kf5-kdoctools.rb
@@ -27,7 +27,7 @@ class Kf5Kdoctools < Formula
 
     system "cmake", ".", *args
     system "make", "install"
-    ln_s Dir["#{share}/kf5"], "#{ENV['HOME']}/Library/Application Support/", :force => true
+    ln_s Dir["#{share}/kf5"], "#{Etc.getpwuid.dir}/Library/Application Support/", :force => true
     prefix.install "install_manifest.txt"
   end
   def caveats; <<-EOS.undent
```

**Comment by haraldF** [comment]
Applied, thank you very much for the patch!

**Comment by seanhoughton** [comment]
Thanks for the fix! And thanks to haraldF for the tap in general.

**Comment by Algorithmus** [comment]
This also happens in kf5 extra cmake modules. Same fix appears to work.
