### ISSUE TITLE
KF5Parts missing

### ISSUE THREAD

**Issue by Paktosan** [haraldF/homebrew-kf5#60]
When installing kdelibs4support it can find KF5Parts, can you fix that?

`Could not find a package configuration file provided by "KF5Parts"
  (requested version 5.22.0) with any of the following names:

```
KF5PartsConfig.cmake
kf5parts-config.cmake
```

  Add the installation prefix of "KF5Parts" to CMAKE_PREFIX_PATH or set
  "KF5Parts_DIR" to a directory containing one of the above files.  If
  "KF5Parts" provides a separate development package or SDK, be sure it has
  been installed.`

**Comment by zavorka** [comment]
#64

**Comment by krf** [comment]
Patch merged.
