### ISSUE TITLE
KDevelop has no icons.

### ISSUE THREAD

**Issue by yurikoles** [haraldF/homebrew-kf5#67]
After an investigation with @krf we have realized that kdevelop doesn't load icons from standard path and we need to do

`ln -sf /usr/local/Cellar/kf5-breeze-icons/5.25.0/share/icons/breeze/breeze-icons.rcc ~/Library/Application\ Support/kdevelop/icontheme.rcc`

**Comment by sadhen** [comment]
Also kate has no icons. Thanks, @yurikoles 

`ln -sf /usr/local/Cellar/kf5-breeze-icons/5.25.0/share/icons/breeze/breeze-icons.rcc ~/Library/Application\ Support/kate/icontheme.rcc` works
