### ISSUE TITLE
Already installed qt5 with d-bus

### ISSUE THREAD

**Issue by nigehban** [haraldF/homebrew-kf5#73]
I've already installed qt5 in my mac 
<img width="631" alt="screen shot 2017-01-01 at 2 04 13 am" src="https://cloud.githubusercontent.com/assets/15114973/21579535/61a877c6-cfbe-11e6-9f74-3449c0b92ca8.png">
Why does brew install qt5 again when I try to install kf5 ?
<img width="943" alt="screen shot 2017-01-01 at 2 04 38 am" src="https://cloud.githubusercontent.com/assets/15114973/21579536/7f348294-cfbe-11e6-810d-1b6eb5185092.png">

**Comment by haraldF** [comment]
Qt 5.8 formula gets rid of the --with-dbus requirement, I guess once we apply https://github.com/haraldF/homebrew-kf5/pull/80 this should not happen any more.
