### ISSUE TITLE
Error while installing kdevplatform

### ISSUE THREAD

**Issue by deaDvo100shuB** [haraldF/homebrew-kf5#76]
Cmake has error while compiling kdevplatform.

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> /tmp/kdevplatform-20170119-39966-v9grv2/language/Boost_INCLUDE_DIR

But i already have boost installing from homebrew.

[01.cmake.txt](https://github.com/haraldF/homebrew-kf5/files/715889/01.cmake.txt)

**Comment by haraldF** [comment]
Problem was that boost wasn't a dependency for kdevplatform. Please re-open if my fix didn't help :)
